server:
    port: 8081
spring:
    jpa:
        hibernate:
            ddl-auto: create-drop
    h2:
        console:
            enabled: true
        path: /h2
    datasource:
        url: jdbc:h2:file:~/test
        username: sa
        password:
        driverClassName: org.h2.Driver
rss:
    url: "https://a1on.mk/feed?format=xml"